In [1]:
import numpy as np

docs = ['go india','india india','hip hip hurray','jeetega bhai jeetega india jeetega','bharat mata ki jai','kohli kohli','sachin sachin','dhoni dhoni','modi ji ki  jai','inquilab zindabadj']

docs

['go india',
 'india india',
 'hip hip hurray',
 'jeetega bhai jeetega india jeetega',
 'bharat mata ki jai',
 'kohli kohli',
 'sachin sachin',
 'dhoni dhoni',
 'modi ji ki  jai',
 'inquilab zindabadj']

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='NA')

tokenizer.fit_on_texts(docs)

tokenizer.word_index

{'NA': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabadj': 18}

In [7]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabadj', 1)])

In [9]:
tokenizer.document_count

10

In [10]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [14]:
from keras.utils import pad_sequences

ps = pad_sequences(sequences,padding='post')



In [15]:
ps

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]])

In [16]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [47]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

# X_train[:10]
y_train[0]


1

In [20]:
print(f"X_train no of instances = {X_train.shape} and X_test no of instances = {X_test.shape}")


X_train no of instances = (25000,) and X_test no of instances = (25000,)


In [21]:
print(f"Why we need padding because")
print(f"no of words in X_train[0] is {len(X_train[0])} and is not equal to X_train[1]i.e {len(X_train[1])}" )

Why we need padding because
no of words in X_train[0] is 218 and is not equal to X_train[1]i.e 189


In [22]:
from keras.utils import pad_sequences

In [61]:
X_train = pad_sequences(X_train,padding='post')
X_test = pad_sequences(X_test,padding='post')
len(X_train[0])

2494

In [24]:
print(len(X_train[0]))

50


In [62]:

model = Sequential()

model.add(SimpleRNN(32,input_shape=(2494,1),return_sequences=False))
model.add(Dense(1,activation= 'sigmoid'))
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [63]:
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs= 5,validation_data=[X_test,y_test])

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 594s 755ms/step - accuracy: 0.4967 - loss: 0.6944 - val_accuracy: 0.5040 - val_loss: 0.6934
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 609s 779ms/step - accuracy: 0.5037 - loss: 0.6940 - val_accuracy: 0.4971 - val_loss: 0.6949
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 56295s 72s/step - accuracy: 0.4998 - loss: 0.6944 - val_accuracy: 0.5024 - val_loss: 0.6937
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 3038s 4s/step - accuracy: 0.5053 - loss: 0.6937 - val_accuracy: 0.5000 - val_loss: 0.6934
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 642s 821ms/step - accuracy: 0.5033 - loss: 0.6934 - val_accuracy: 0.5000 - val_loss: 0.6936


In [57]:
# X_test[0]
# y_test[0]
y = model.predict(np.array([X_test[0]]))
print(f"X-test[0] = {X_test[0]} and actual sentiment y[0] = {y_test[0]} also predicted sentiment is y = {y}")

In [52]:
y = model.predict(np.array([X_test[0]]))
y


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[0.47406605]], dtype=float32)

In [27]:
import numpy as np

docs = ['go india','india india','hip hip hurray','jeetega bhai jeetega india jeetega','bharat mata ki jai','kohli kohli','sachin sachin','dhoni dhoni','modi ji ki  jai','inquilab zindabadj']

docs

['go india',
 'india india',
 'hip hip hurray',
 'jeetega bhai jeetega india jeetega',
 'bharat mata ki jai',
 'kohli kohli',
 'sachin sachin',
 'dhoni dhoni',
 'modi ji ki  jai',
 'inquilab zindabadj']

In [32]:
from tensorflow.keras.preprocessing.text import Tokenizer

tok = Tokenizer()

tok.fit_on_texts(docs)

seq = tok.texts_to_sequences(docs)
seq

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [34]:
# tok.word_counts

from keras.utils import pad_sequences

pd = pad_sequences(seq,padding='post')
pd

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

In [31]:
len(tok.word_index)b

17

In [42]:
model = Sequential()
model.add(Embedding(input_dim =18, output_dim=3, input_length=5, name='embedding_layer'))
# model.add(Flatten())
model.add(SimpleRNN(32,input_shape(2494,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
# Compile the model (not necessary for just retrieving embeddings)
model.compile(optimizer='adam', loss='binary_crossentropy')

model.fit(X_train,y_train,epochs= 100,validation_data=[X_test,y_test])


y = model.predict(np.array([X_test[0]]))
print(f"X-test[0] = {X_test[0]} and actual sentiment y[0] = {y_test[0]} also predicted sentiment is y = {y}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 261ms/step
Embeddings:
 [[ 9.2772618e-03  4.8284642e-03 -1.4964320e-02  6.0039274e-03
  -4.9279284e-02  6.7010894e-03  3.0705009e-02  4.6673741e-02
   4.6001188e-03  3.3946410e-03 -4.8492815e-02  5.5555478e-03
   3.9355125e-02  2.0880137e-02  2.4199057e-02 -4.8492815e-02
   5.5555478e-03  3.9355125e-02  2.0880137e-02  2.4199057e-02
  -4.8492815e-02  5.5555478e-03  3.9355125e-02  2.0880137e-02
   2.4199057e-02]
 [ 6.7010894e-03  3.0705009e-02  4.6673741e-02  4.6001188e-03
   3.3946410e-03  6.7010894e-03  3.0705009e-02  4.6673741e-02
   4.6001188e-03  3.3946410e-03 -4.8492815e-02  5.5555478e-03
   3.9355125e-02  2.0880137e-02  2.4199057e-02 -4.8492815e-02
   5.5555478e-03  3.9355125e-02  2.0880137e-02  2.4199057e-02
  -4.8492815e-02  5.5555478e-03  3.9355125e-02  2.0880137e-02
   2.4199057e-02]
 [ 1.3114620e-02  4.2061534e-02  1.9568253e-02 -1.0426104e-02
  -3.0982733e-02  1.3114620e-02  4.2061534e-02  1.9568253e-02
  -1.0426104e-02 -3.0982733e-02 -4.9922753e-